FROM alpine:latest
ARG VERSION=1.7.0
RUN apk update && \
    apk upgrade && \ 
    apk add wget && \
    wget https://github.com/wercker/stern/releases/download/$VERSION/stern_linux_amd64 && \
    chmod +x stern_linux_amd64 && \
    mv stern_linux_amd64 /usr/local/bin/stern 
ENTRYPOINT ["stern"]


