FROM fedora:29
COPY ./setup-dotfiles /root/setup-dotfiles 
RUN dnf update --refresh -y && \
    dnf install\
    git\ 
    vim\ 
    ranger\ 
    curl\ 
    wget\
    python\
    python3\
    ansible\
    zsh\
    fish -y 
CMD "bash"